language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
before_script:
  - "npm i gatsby@2.2.9 -g"
  - "npm ci"
script:
  - "npm run deploy"